# Generated by Django 3.1.4 on 2021-01-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fajr', models.CharField(blank=True, max_length=100, null=True)),
                ('dohr', models.CharField(blank=True, max_length=100, null=True)),
                ('aser', models.CharField(blank=True, max_length=100, null=True)),
                ('maghrib', models.CharField(blank=True, max_length=100, null=True)),
                ('aisha', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
